# Generated by Django 3.0.3 on 2020-03-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custr',
            new_name='customer',
        ),
    ]
